### ISSUE TITLE
0.4.0 Checklist

### ISSUE THREAD

**Issue by nshaaban-cPacket** [1c3t3a/rust-socketio#124]
It's that time @1c3t3a , might want to make a branch. How servers are implemented informs discussion about what the best interface method is (for 0.3.X).

0.4.0:
- [ ] Polling server added
- [ ] Websocket server added
- [ ] Socket implemented
- [ ] Tests written
  - [ ] Unit tests
  - [ ] Integration tests against rust_socketio client
  - [ ] Integration tests for client against server
  - [ ] Integration tests against nodejs reference impl
  - [ ] Performance tests
  - [ ] Maintain coverage
- [ ] Interface written

**Comment by nshaaban-cPacket** [comment]
@1c3t3a It would be easier to implement 0.4.0 if we used async internally, but didn't expose. That alright with you? Async internally but synchronous interfaces? Using https://docs.rs/futures/0.3.17/futures/sink/index.html https://docs.rs/futures/0.3.17/futures/stream/index.html# internally, then consuming the sinks into callbacks.

**Comment by 1c3t3a** [comment]
Yes, just opened it!

**Comment by nshaaban-cPacket** [comment]
@1c3t3a how does this look for a the closure based callback interface for the server? This interface will involve several Arc Mutex locks, after/during implementation we can discuss other interfaces that are more rusty.
```rust
async fn main() {
    let server = ServerBuilder::new(4202).connect().await?;
    builder.on("connection", |socket, server| {
        socket.on("message", |message, socket, server| {
            socket.emit_with_ack("hello awk", |socket, server| {
                // awked
            }).await?;
        });
        socket.on("heartbeat", |socket, server| {

        });
        socket.on("error", |message, socket, server| {

        });
        socket.on("close", |socket, server| {

        });
        socket.emit("hello client").await?;
    });
    server.emit("hello").await?;

}
```

**Comment by 1c3t3a** [comment]
I would honestly prefer the former, as it sticks more to the socketio API. Also the latter could be more difficult when reacting to a custom event. And I honestly like the `Into<Event>` Generic bounds which allow passing in strings in a type safe manner. What do you think @nshaaban-cPacket?

**Comment by nshaaban-cPacket** [comment]
Agreed, the former make more sense. I'm writing the code in such a way that should enable us to write different API interfaces in the future (like more rusty/streams ones) .

**Comment by 1c3t3a** [comment]
With 0.4.0 being about reconnect refactor, we should either rename this to 0.5.0 or close.

**Comment by ctrlaltf24** [comment]
Looks like someone beat us to it https://github.com/Totodore/socketioxide implemented as a tower layer, interesting
