### ISSUE TITLE
0.3.X Checklist

### ISSUE THREAD

**Issue by nshaaban-cPacket** [1c3t3a/rust-socketio#72]
0.3.X:
- [ ] finalize socketio iter interface? or postpone until 0.4.0?
- [ ] All public types implement Debug, Sync, Send
  - [ ] Data types implement Eq and Clone

**Comment by nshaaban-cPacket** [comment]
0.3.0:
- [x] Resolve relevant TODOs
- [x] Be within +/- 20% performance of present main (see https://github.com/1c3t3a/rust-socketio/pull/71 )
- [x] Documentation
  - [x] remove warnings about &Socket callbacks (feature reverted)
- [x] Increase test coverage to around pre-refactor levels
- [x] Change-log (to public interfaces)
  - [x] Add deprecation to 0.2.0 informing users how to update. https://github.com/1c3t3a/rust-socketio/pull/85
- [x] Separate engineio into separate crate
  - [x] Merge https://github.com/1c3t3a/rust-socketio/pull/89 
- [x] Allow socketio to specify transport https://github.com/1c3t3a/rust-socketio/issues/94
- [x] https://github.com/1c3t3a/rust-socketio/issues/90
- [X] Address concerns in comments
  - [X] https://github.com/1c3t3a/rust-socketio/pull/101#discussion_r698482795
  - [X] https://github.com/1c3t3a/rust-socketio/pull/101#discussion_r698477692
- [X] Make sure intermittent failure on https://github.com/1c3t3a/rust-socketio/pull/97 does not continue.
